//Matheus Kodi Y. Ra2503557
package com.mycompany.projetofinal;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class RelatorioBlusaFrio extends javax.swing.JFrame {
    private static RelatorioBlusaFrio relBluUnico;
    public RelatorioBlusaFrio() {
        initComponents();
    }
    public static RelatorioBlusaFrio getRelatorioBlusaFrio(){
        if(relBluUnico == null){
            relBluUnico = new RelatorioBlusaFrio();
        }
        return relBluUnico;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaBlusa = new javax.swing.JTable();
        labTituloRelatorio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tabelaBlusa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, "", null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Marca", "Modelo", "Cor", "Material", "Preco", "Tamanho", "Genero", "Desconto Aplicado", "Descricao", "Capuz", "Forro", "Ziper"
            }
        ));
        tabelaBlusa.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                tabelaBlusaComponentAdded(evt);
            }
        });
        tabelaBlusa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaBlusaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaBlusa);

        labTituloRelatorio.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labTituloRelatorio.setText("RELATORIO BLUSA DE FRIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1046, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addComponent(labTituloRelatorio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(labTituloRelatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaBlusaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_tabelaBlusaComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaBlusaComponentAdded

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listarTabela();
    }//GEN-LAST:event_formWindowActivated

    private void tabelaBlusaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaBlusaMouseClicked
        valorPegoTabela();
    }//GEN-LAST:event_tabelaBlusaMouseClicked
    public void valorPegoTabela(){
        String valorLinha = "";
        int posicaoLinha = tabelaBlusa.getSelectedRow();
        
        for(int col = 0; col < tabelaBlusa.getColumnCount(); col++){
            valorLinha += tabelaBlusa.getModel().getValueAt(posicaoLinha, col).toString();
            
            if(col+1 < tabelaBlusa.getColumnCount()){
                valorLinha += " - ";
            }
        }
        JOptionPane.showMessageDialog(
                null,
                "Valor obtido da tabela: "+valorLinha,
                "Tabela",
                2
        );
    }
    public void listarTabela(){
        DefaultTableModel tabela = (DefaultTableModel)tabelaBlusa.getModel();
        int posicaoLinha = 0;
        tabela.setRowCount(posicaoLinha);
        
        for(BlusaFrio blu : BancoRoupa.getBancoRoupa().getBdBlusaFrio()){
            tabela.insertRow(posicaoLinha, new Object[]{blu.getCodigo(), blu.getMarca(), blu.getModelo(), blu.getCor(), blu.getMaterial(), blu.getPreco(), blu.getTamanho(), blu.getGenero(), blu.getDesconto(), blu.getDescricao(), blu.getCapuz(), blu.getForro(), blu.getZiper()} );
            posicaoLinha++;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labTituloRelatorio;
    private javax.swing.JTable tabelaBlusa;
    // End of variables declaration//GEN-END:variables
}
