//Matheus Kodi Y. Ra2503557
package com.mycompany.projetofinal;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class RelatorioCamiseta extends javax.swing.JFrame {
    private static RelatorioCamiseta relCamUnico;
    public RelatorioCamiseta() {
        initComponents();
    }
    public static RelatorioCamiseta getRelatorioCamiseta(){
        if(relCamUnico == null){
            relCamUnico = new RelatorioCamiseta();
        }
        return relCamUnico;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCamiseta = new javax.swing.JTable();
        labTituloRelatorio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tabelaCamiseta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, "", null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Marca", "Modelo", "Cor", "Material", "Preco", "Tamanho", "Genero", "Tipo de Manga", "Corte", "Desconto Aplicado", "Gola", "Estampada", "Descricao"
            }
        ));
        tabelaCamiseta.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                tabelaCamisetaComponentAdded(evt);
            }
        });
        tabelaCamiseta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaCamisetaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaCamiseta);

        labTituloRelatorio.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labTituloRelatorio.setText("RELATORIO CAMISETA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(labTituloRelatorio)
                .addGap(339, 366, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labTituloRelatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaCamisetaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_tabelaCamisetaComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaCamisetaComponentAdded

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listarTabela();
    }//GEN-LAST:event_formWindowActivated

    private void tabelaCamisetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaCamisetaMouseClicked
        valorPegoTabela();
    }//GEN-LAST:event_tabelaCamisetaMouseClicked
    public void valorPegoTabela(){
        String valorLinha = "";
        int posicaoLinha = tabelaCamiseta.getSelectedRow();
        
        for(int col = 0; col < tabelaCamiseta.getColumnCount(); col++){
            valorLinha += tabelaCamiseta.getModel().getValueAt(posicaoLinha, col).toString();
            
            if(col+1 < tabelaCamiseta.getColumnCount()){
                valorLinha += " - ";
            }
        }
        JOptionPane.showMessageDialog(
                null,
                "Valor obtido da tabela: "+valorLinha,
                "tabela",
                2
        );
    }
    public void listarTabela(){
        DefaultTableModel tabela = (DefaultTableModel)tabelaCamiseta.getModel();
        int posicaoLinha = 0;
        tabela.setRowCount(posicaoLinha);
        for(Camiseta cam : BancoRoupa.getBancoRoupa().getBdCamiseta()){
            tabela.insertRow(posicaoLinha, new Object[]{cam.getCodigo(), cam.getMarca(), cam.getModelo(), cam.getCor(), cam.getMaterial(), cam.getPreco(), cam.getTamanho(), cam.getGenero(), cam.getTipoManga(), cam.getCorte(), cam.getDesconto(), cam.getGola(), cam.getEstampada(), cam.getDescricao()} );
            posicaoLinha++;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labTituloRelatorio;
    private javax.swing.JTable tabelaCamiseta;
    // End of variables declaration//GEN-END:variables
}
