//Matheus Kodi Y. Ra2503557
package com.mycompany.projetofinal;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class RelatorioCalca extends javax.swing.JFrame {
    private static RelatorioCalca relCalUnico;
    public RelatorioCalca() {
        initComponents();
    }
    public static RelatorioCalca getRelatorioCalca(){
        if(relCalUnico == null){
            relCalUnico = new RelatorioCalca();
        }
        return relCalUnico;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCalca = new javax.swing.JTable();
        labTituloRelatorio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tabelaCalca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, "", null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Marca", "Modelo", "Cor", "Material", "Preco", "Tamanho", "Genero", "Desconto Aplicado", "Descricao", "Bolso Faca", "Bolso Traseiro", "Bolso Lateral", "Cinto", "Elastico"
            }
        ));
        tabelaCalca.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                tabelaCalcaComponentAdded(evt);
            }
        });
        tabelaCalca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaCalcaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaCalca);

        labTituloRelatorio.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labTituloRelatorio.setText("RELATORIO CALCA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(labTituloRelatorio)
                .addContainerGap(441, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labTituloRelatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaCalcaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_tabelaCalcaComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaCalcaComponentAdded

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listarTabela();
    }//GEN-LAST:event_formWindowActivated

    private void tabelaCalcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaCalcaMouseClicked
        valorPegoTabela();
    }//GEN-LAST:event_tabelaCalcaMouseClicked
    public void valorPegoTabela(){
        String valorLinha = "";
        int posicaoLinha = tabelaCalca.getSelectedRow();
        
        for(int col = 0; col < tabelaCalca.getColumnCount(); col++){
            valorLinha += tabelaCalca.getModel().getValueAt(posicaoLinha, col).toString();
            
            if(col+1 < tabelaCalca.getColumnCount()){
                valorLinha += " - ";
            }
        }
        JOptionPane.showMessageDialog(
                null,
                "Valor obtido da tabela: "+valorLinha,
                "Tabela",
                2
        );
    }
    public void listarTabela(){
        DefaultTableModel tabela = (DefaultTableModel)tabelaCalca.getModel();
        int posicaoLinha = 0;
        tabela.setRowCount(posicaoLinha);
        
        for(Calca cal : BancoRoupa.getBancoRoupa().getBdCalca()){
            tabela.insertRow(posicaoLinha, new Object[]{cal.getCodigo(), cal.getMarca(), cal.getModelo(), cal.getCor(), cal.getMaterial(), cal.getPreco(), cal.getTamanho(), cal.getGenero(), cal.getDesconto(), cal.getDescricao(), cal.getBolsoFaca(), cal.getBolsoTraseiro(), cal.getBolsoLateral(), cal.getCinto(), cal.getElasticoCintura()} );
            posicaoLinha++;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labTituloRelatorio;
    private javax.swing.JTable tabelaCalca;
    // End of variables declaration//GEN-END:variables
}
